Participation/custom question
itsAndL/proctor pull request #35
Opened 2024-09-19 15:10 UTC by abdokin

Implement Custom question participation

2024-09-19 18:14 UTC, itsAndL commented on db/migrate/20240919102957_update_custom_question_responses.rb
> +      t.remove :duration_seconds
This is not reversible

2024-09-19 21:03 UTC, itsAndL requested changes

2024-09-19 21:06 UTC, itsAndL commented
***This is not on the fullscreen mode, not under the monitoring***

![Screenshot 2024-09-19 205524](https://github.com/user-attachments/assets/3f754add-20c8-4565-b451-9a8445ecb3cf)

2024-09-19 21:08 UTC, itsAndL commented
***this also not under monitoring not on fullscreen mode***

![Screenshot 2024-09-19 205714](https://github.com/user-attachments/assets/072c028b-d8ae-44d9-8c41-8a019e56329c)

2024-09-19 21:08 UTC, itsAndL commented
***this need to be not on full screen***

![Screenshot 2024-09-19 212804](https://github.com/user-attachments/assets/13855c53-e643-467e-9e0f-f6f4fecb5514)

2024-09-19 21:10 UTC, itsAndL commented
***why the style of this is broken***

![Screenshot 2024-09-19 210528](https://github.com/user-attachments/assets/2744fc62-9d64-42a7-a9c8-149d9eb0b849)

2024-09-19 21:12 UTC, itsAndL commented
***the "Rate answer" should be on the right***

![Screenshot 2024-09-19 210327](https://github.com/user-attachments/assets/61b0d136-5f4b-42b1-9cbc-fa1027a01f15)

2024-09-19 21:13 UTC, itsAndL commented
***why the checkboxes are disappeared***

![Screenshot 2024-09-19 213848](https://github.com/user-attachments/assets/904e034d-bf53-46a8-bdc0-45410b5e4fe1)

2024-09-19 21:14 UTC, itsAndL commented
***Assessment has 2 tests + 2 custom questions: i passed the 2 tests and it redirected me to the checkout page. why? i didn't pass custom questions, it should take me to the assessment***

2024-09-19 21:26 UTC, itsAndL commented
***Why you didn't handle the time for practice questions like how you do for questions, we need to have consistency***
***The time is related to the whole practice questions, not each practice question***

![image](https://github.com/user-attachments/assets/33f32f4c-52ce-4288-885e-bb18e60b46bf)

2024-09-19 22:13 UTC, abdokin commented on app/javascript/controllers/question_answer_controller.js
> +      // remainingTime = this.initialTime * 1000;
its should be commented i just missed it

2024-09-19 22:15 UTC, abdokin commented on app/models/custom_question_response.rb
> +    custom_question.duration_seconds.nil? || custom_question.duration_seconds.zero?
its will make much more sense, got it

2024-09-19 22:17 UTC, abdokin commented on app/services/assessment_participation_service.rb
> +      response.save!(validate: false)
its was the right thing to do because we used to have validation on customQuestionReponse but i did remove it.

2024-09-19 22:23 UTC, abdokin commented on app/views/candidate/custom_questions/show.html.erb
> +</main>
i think im going to move it to View Component & and call same start cuz its make more sense here thanks.

2024-09-19 22:24 UTC, abdokin commented on config/routes.rb
> +    end
alright

2024-09-20 11:01 UTC, itsAndL commented on app/components/participation_feedback_component.html.erb
> +<% end %>
we don't need this no more cause the custom question doesn't have a feedback only the test

2024-09-20 11:03 UTC, itsAndL commented on app/components/participation_setup_component.html.erb
> +<% end %>
indentation style (2 spaces, not 4 spaces)

2024-09-20 11:06 UTC, itsAndL commented on app/components/participation_setup_component.html.erb
> +        "monitoring-assessment-participation-hash-id-value" => @assessment_participation.hashid
this line is duplicated, you get it from monitoring_data

2024-09-20 11:27 UTC, abdokin commented
I did leave the ParticipationFeedback component because i found testgorilla give you to specify  the feedback in case we want to reuse it, its won't cause a problem for now

2024-09-20 13:37 UTC, itsAndL approved these changes

2024-09-20 13:37 UTC, merged