Refactor/categories to enums
itsAndL/proctor pull request #69
Opened 2024-10-30 16:09 UTC by abdokin

2024-10-30 16:14 UTC, abdokin commented
![](https://github.trello.services/images/mini-trello-icon.png) [For the custom questions category and test category, transfer them from table to enum](https://trello.com/c/hbVQ6LFQ/48-for-the-custom-questions-category-and-test-category-transfer-them-from-table-to-enum)

2024-10-30 16:32 UTC, itsAndL requested changes

2024-10-30 16:32 UTC, itsAndL commented on app/queries/test_query.rb
> +  def filter_by_categories(categories: nil)
i see here that you don't use this param "categories"

2024-10-30 16:32 UTC, itsAndL commented on app/components/filter_component.rb
> +        # name, value, checked, id, label
This comment for what?

2024-10-30 16:32 UTC, itsAndL commented on app/components/filter_component.rb
> +          category,
in test_category_section you called .to_s (category.to_s), which one to use?

2024-10-31 07:31 UTC, itsAndL requested changes

2024-10-31 07:31 UTC, itsAndL commented on db/schema.rb
>    end
this table needs to be drop, the same for test_categories
+ when i rollback i need to get the same table

2024-10-31 07:31 UTC, itsAndL commented on db/schema.rb
> +    t.bigint 'custom_question_category_id'
the reference to be remove the same for test_categories, instead a "category" column of type integer, also when i rollback get the same reference

2024-10-31 12:07 UTC, itsAndL approved these changes

2024-10-31 12:07 UTC, merged