Add email search capability for temporary candidates
itsAndL/proctor pull request #82
Opened 2024-11-08 11:06 UTC by abdokin

2024-11-08 11:06 UTC, abdokin commented
![](https://github.trello.services/images/mini-trello-icon.png) [in assessment when i search for a candidate (which he's a temp candidate) i get no result](https://trello.com/c/hp55FMdj/84-in-assessment-when-i-search-for-a-candidate-which-hes-a-temp-candidate-i-get-no-result)

2024-11-08 16:41 UTC, itsAndL requested changes
Can we improve the search to not just search within beginning

for example, i have a name or email "John Doe", "john.doe@example.com"

if I search with John i will get the result if Doe I will not, cause it's in the middle

2024-11-08 16:44 UTC, itsAndL requested changes

2024-11-11 11:10 UTC, itsAndL approved these changes

2024-11-11 11:11 UTC, merged